apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-demo
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: fastapi-demo